import { randomBytes } from 'node:crypto';
import { chmod, mkdir, open, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { GatewayError } from './errors.mjs';

const gatewayDirectory = dirname(fileURLToPath(import.meta.url));
const bundledCodexBinary = join(
  gatewayDirectory,
  'node_modules',
  '.bin',
  process.platform === 'win32' ? 'codex.cmd' : 'codex',
);

export const DEFAULT_ALLOWED_ORIGINS = Object.freeze([
  'https://none0enon.github.io',
  'https://appassets.androidplatform.net',
]);

export const DISABLED_CODEX_FEATURES = Object.freeze([
  'apps',
  'browser_use',
  'browser_use_external',
  'browser_use_full_cdp_access',
  'computer_use',
  'code_mode_host',
  'deferred_executor',
  'enable_mcp_apps',
  'executor_capability_discovery',
  'goals',
  'hooks',
  'image_generation',
  'in_app_browser',
  'multi_agent',
  'multi_agent_v2',
  'plugin_sharing',
  'plugins',
  'recommended_plugins',
  'remote_plugin',
  'request_permissions_tool',
  'shell_tool',
  'shell_snapshot',
  'skill_mcp_dependency_install',
  'skill_search',
  'sleep_tool',
  'standalone_web_search',
  'tool_suggest',
  'unified_exec',
  'unified_exec_tty',
  'view_image',
  'workspace_dependencies',
]);

const CONFIG_TOML = `# Generated by math-reader-codex.
# This CODEX_HOME is intentionally separate from desktop/CLI credentials.
forced_login_method = "chatgpt"
cli_auth_credentials_store = "file"
sandbox_mode = "read-only"
approval_policy = "never"
web_search = "disabled"
model_provider = "math_reader_http"

# Keep long lecture responses on WebSocket. Large images are uploaded separately
# before starting the single model turn, avoiding oversized WebSocket messages.
# Built-in provider IDs are reserved; keep the same ChatGPT endpoint and login.
[model_providers.math_reader_http]
name = "OpenAI"
base_url = "https://chatgpt.com/backend-api/codex"
wire_api = "responses"
requires_openai_auth = true
supports_websockets = true

[analytics]
enabled = false

[features]
${DISABLED_CODEX_FEATURES.map((name) => `${name} = false`).join('\n')}
skip_host_skill_discovery = true

[tools.experimental_request_user_input]
enabled = false
`;

function integer(value, fallback, { min, max }) {
  if (value === undefined || value === '') return fallback;
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed) || parsed < min || parsed > max) {
    throw new GatewayError('invalid_configuration', `Expected an integer from ${min} to ${max}.`, 500);
  }
  return parsed;
}

function absoluteOrResolved(value, fallback) {
  const candidate = value || fallback;
  return isAbsolute(candidate) ? candidate : resolve(gatewayDirectory, candidate);
}

export function loadConfig(env = process.env) {
  const stateDirectory = absoluteOrResolved(env.MATH_READER_GATEWAY_STATE_DIR, '.state');
  const tokenFile = absoluteOrResolved(
    env.MATH_READER_GATEWAY_TOKEN_FILE,
    join(stateDirectory, 'gateway-token'),
  );
  const extraOrigins = (env.MATH_READER_GATEWAY_ALLOWED_ORIGINS || '')
    .split(',')
    .map((origin) => origin.trim())
    .filter(Boolean);

  return {
    gatewayDirectory,
    stateDirectory,
    codexHome: join(stateDirectory, 'codex-home'),
    isolatedHome: join(stateDirectory, 'home'),
    workspaceDirectory: join(stateDirectory, 'workspace'),
    temporaryDirectory: join(stateDirectory, 'tmp'),
    tokenFile,
    codexBin: env.MATH_READER_CODEX_BIN || bundledCodexBinary,
    host: env.MATH_READER_GATEWAY_HOST || '127.0.0.1',
    port: integer(env.MATH_READER_GATEWAY_PORT, 4747, { min: 1, max: 65535 }),
    requestTimeoutMs: integer(env.MATH_READER_GATEWAY_TIMEOUT_MS, 600_000, {
      min: 1_000,
      max: 3_600_000,
    }),
    // Generation time for one lecture job, counted from when it leaves the
    // queue. ChatGPT was observed to end a single HTTP response stream after
    // about 15 minutes; Codex then retries, so a long lecture can need far more.
    lectureTimeoutMs: integer(env.MATH_READER_GATEWAY_LECTURE_TIMEOUT_MS, 3_600_000, {
      min: 60_000,
      max: 14_400_000,
    }),
    maxQueueDepth: integer(env.MATH_READER_GATEWAY_MAX_QUEUE, 8, { min: 0, max: 100 }),
    maxBodyBytes: integer(env.MATH_READER_GATEWAY_MAX_BODY_BYTES, 96 * 1024 * 1024, {
      min: 1024,
      max: 256 * 1024 * 1024,
    }),
    allowedOrigins: new Set([...DEFAULT_ALLOWED_ORIGINS, ...extraOrigins]),
    tlsCertificateFile: env.MATH_READER_GATEWAY_TLS_CERT || null,
    tlsKeyFile: env.MATH_READER_GATEWAY_TLS_KEY || null,
    allowInsecureRemote: env.MATH_READER_GATEWAY_ALLOW_INSECURE_REMOTE === '1',
  };
}

async function writeAtomic(path, contents, mode) {
  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  const temporaryPath = `${path}.${process.pid}.${randomBytes(6).toString('hex')}.tmp`;
  await writeFile(temporaryPath, contents, { mode });
  await chmod(temporaryPath, mode);
  await rename(temporaryPath, path);
}

async function ensureToken(path) {
  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  let created = false;
  try {
    const handle = await open(path, 'wx', 0o600);
    try {
      await handle.writeFile(`${randomBytes(32).toString('base64url')}\n`);
      created = true;
    } finally {
      await handle.close();
    }
  } catch (error) {
    if (error?.code !== 'EEXIST') throw error;
  }
  await chmod(path, 0o600);
  const token = (await readFile(path, 'utf8')).trim();
  if (!/^[A-Za-z0-9_-]{40,}$/.test(token)) {
    throw new GatewayError(
      'invalid_token_file',
      `Gateway token file is empty or malformed: ${path}`,
      500,
    );
  }
  return { token, created };
}

export async function ensureRuntimeState(config) {
  for (const directory of [
    config.stateDirectory,
    config.codexHome,
    config.isolatedHome,
    config.workspaceDirectory,
    config.temporaryDirectory,
  ]) {
    await mkdir(directory, { recursive: true, mode: 0o700 });
    await chmod(directory, 0o700);
  }
  await writeAtomic(join(config.codexHome, 'config.toml'), CONFIG_TOML, 0o600);
  const token = await ensureToken(config.tokenFile);
  return { ...token, configFile: join(config.codexHome, 'config.toml') };
}

const PASSTHROUGH_ENV = new Set([
  'LANG',
  'LOGNAME',
  'NO_PROXY',
  'PATH',
  'SSL_CERT_DIR',
  'SSL_CERT_FILE',
  'TZ',
  'USER',
  'http_proxy',
  'https_proxy',
  'no_proxy',
  'HTTP_PROXY',
  'HTTPS_PROXY',
]);

export function sanitizedCodexEnvironment(baseEnvironment, config) {
  const environment = {};
  for (const [name, value] of Object.entries(baseEnvironment || {})) {
    if (value === undefined) continue;
    if (PASSTHROUGH_ENV.has(name) || name.startsWith('LC_')) environment[name] = value;
  }
  if (process.platform === 'win32') {
    for (const name of ['ComSpec', 'PATHEXT', 'SystemRoot', 'WINDIR']) {
      if (baseEnvironment?.[name]) environment[name] = baseEnvironment[name];
    }
  }
  environment.HOME = config.isolatedHome;
  environment.CODEX_HOME = config.codexHome;
  environment.TMPDIR = config.temporaryDirectory;
  environment.TMP = config.temporaryDirectory;
  environment.TEMP = config.temporaryDirectory;
  environment.NO_COLOR = '1';
  return environment;
}

export function appServerArguments() {
  return [
    'app-server',
    '--stdio',
    '--strict-config',
    '--enable',
    'skip_host_skill_discovery',
    ...DISABLED_CODEX_FEATURES.flatMap((name) => ['--disable', name]),
  ];
}

export function isAllowedOrigin(origin, allowedOrigins) {
  if (!origin) return true;
  if (allowedOrigins.has(origin)) return true;
  try {
    const url = new URL(origin);
    return (
      (url.protocol === 'http:' || url.protocol === 'https:') &&
      (url.hostname === 'localhost' || url.hostname === '127.0.0.1' || url.hostname === '[::1]')
    );
  } catch {
    return false;
  }
}

export async function readTlsOptions(config) {
  if (!config.tlsCertificateFile && !config.tlsKeyFile) return null;
  if (!config.tlsCertificateFile || !config.tlsKeyFile) {
    throw new GatewayError(
      'invalid_tls_configuration',
      'Set both MATH_READER_GATEWAY_TLS_CERT and MATH_READER_GATEWAY_TLS_KEY.',
      500,
    );
  }
  return {
    cert: await readFile(config.tlsCertificateFile),
    key: await readFile(config.tlsKeyFile),
  };
}
